#!/bin/bash

set -e
set -u

files=$(find projects/{01,02,03,05} -name '*.tst' -type f | grep -v 'Memory.tst')

echo "--- Running hardware simulator tests ---"
[[ -n ${files} ]] && {
    for file in ${files}; do
        echo "Test file: ${file}"
        $(pwd)/tools/HardwareSimulator.sh ${file}
    done
}
echo "--- Finished running hardware simulator tests ---"

echo "--- Running CPU emulator tests ---"
files=$(find projects/04 -name '*.tst' -type f | grep -v 'Fill.tst')
[[ -n ${files} ]] && {
    for file in ${files}; do
        echo "Test file: ${file}"
        $(pwd)/tools/CPUEmulator.sh ${file}
    done
}
echo "--- Finished running CPU emulator tests ---"
